# TensorFlow PRIMER pt1

In [1]:
# importing dependency
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
# create tersors with constant values
scalar=tf.constant(7)
print(scalar,"\n")
# check no of dimentions of a tensor
print(scalar.ndim)

tf.Tensor(7, shape=(), dtype=int32) 

0


In [3]:
# create a vector
vector=tf.constant([10,19,34,23])
print(vector,"\n")

# check the dimention of our vector
print(vector.ndim)

tf.Tensor([10 19 34 23], shape=(4,), dtype=int32) 

1


In [4]:
# create a matrix 
matrix=tf.constant([[10,11],[12,54],[354,23]])
print(matrix)

# check the dimention of our matrix
print(matrix.ndim)

tf.Tensor(
[[ 10  11]
 [ 12  54]
 [354  23]], shape=(3, 2), dtype=int32)
2


In [5]:
# defining datatypes 
matrix2=tf.constant([[12,34],[23,56]],dtype='float')
print(matrix2)

tf.Tensor(
[[12. 34.]
 [23. 56.]], shape=(2, 2), dtype=float32)


In [6]:
# create a tensor (3D matrix)
tensor=tf.constant([[[23,34,23],[23,45,34],[234,45,23]],[[23,45,23],[645,553,23],[87,56,435]]])
print(tensor)

tf.Tensor(
[[[ 23  34  23]
  [ 23  45  34]
  [234  45  23]]

 [[ 23  45  23]
  [645 553  23]
  [ 87  56 435]]], shape=(2, 3, 3), dtype=int32)


### Create Tensor with Variable 

In [7]:
# create the same tensor with tf.Variable() as above
changeable_tensor=tf.Variable([10,7]) # V should be capital
unchangable_tensor=tf.constant([10,7])
print(changeable_tensor, unchangable_tensor)

# changeable_tensor[0]=7 # can't update and assign values here like this
changeable_tensor[0].assign(23) # this works

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)> tf.Tensor([10  7], shape=(2,), dtype=int32)


<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([23,  7], dtype=int32)>

## Creating Radom Tensors 
> USED TO INITIALISE NN AND DEEP LEARNING MODELS WITH RANDOM WEIGHTS

In [8]:
# create two random (but the same tensors)
rand1=tf.random.Generator.from_seed(42) # setting seed for reproduibility
rand1=rand1.normal(shape=(3,2)) # normal distibution

rand2=tf.random.Generator.from_seed(42) # same seed values means same random value generated
rand2=rand2.normal(shape=(3,2))
print(rand1,"\n","\n",rand2)

# remember that the distribution type needs to be the same for the exact copies produced

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32) 
 
 tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


## Shuffling the order of elements in a tensor 
>IMPORTANT FOR STOCHASTIC GRADIENT DESCENT OPTIMIZER IN OUR BACKPROPAGATION ALGORITHM



In [9]:
not_shuffled=tf.constant([[10,7],[23,54],[342,3],[43554,465]])   
print(not_shuffled)           

tf.Tensor(
[[   10     7]
 [   23    54]
 [  342     3]
 [43554   465]], shape=(4, 2), dtype=int32)


In [10]:
# shuffle every time executed
shuffled=tf.random.shuffle(not_shuffled)
print(shuffled)

tf.Tensor(
[[43554   465]
 [  342     3]
 [   10     7]
 [   23    54]], shape=(4, 2), dtype=int32)


In [11]:
# seeding, so the values so they don't change
tf.random.set_seed(42) # Global level random seeding
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[   23,    54],
       [  342,     3],
       [   10,     7],
       [43554,   465]], dtype=int32)>

In [12]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[   10,     7],
       [  342,     3],
       [43554,   465],
       [   23,    54]], dtype=int32)>

### More Tensors

In [13]:
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [14]:
tf.zeros(shape=(3,5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

## NumPy vs Tensors
main difference is that Numpy arrays can't be run on a GPU computing, while tensorflow tensors can be

In [15]:
# Turning NumPy arrays into tensors
import numpy as np
nparr=np.arange(4,10)
print(nparr,"\n")
tensor=tf.constant(nparr)
print(tensor)

[4 5 6 7 8 9] 

tf.Tensor([4 5 6 7 8 9], shape=(6,), dtype=int64)


## Getting info from tensors
- Shape: The length of each dimention of the tensor `tensor.shape`
- Rank: No of tensor dimentions `tensor.ndim`
  - scalar=0
  - vector=1
  - tensor=n
- Axis or Dimention: Aparticular dimention of a tensor `tensor[0], tensor[:,1]`
- Size: The total number of items in the tensor `tf.size(tensor)`

In [16]:
# create a rank 4 tensor (4 dimentions)
rank2tensor=tf.zeros(shape=[3,4,2,8]) # 2X8 ke 4 tensors banao, 3 baar
print(rank2tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0.]]]], shape=(3, 4, 2, 8), dtype=float32)


In [17]:
rank2tensor[0] # gives 1 tensor out of 3, 
# possible tensors here are rank4tensor[0], rank4tensor[1], rank4tensor[2]

<tf.Tensor: shape=(4, 2, 8), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]], dtype=float32)>

In [18]:
print(rank2tensor.shape,'\n',rank2tensor.ndim,'\n',tf.size(rank2tensor))

(3, 4, 2, 8) 
 4 
 tf.Tensor(192, shape=(), dtype=int32)


### Various attributes of a tensor


In [19]:
print("Datatype of every Element:",  rank2tensor.dtype)
print("Number of Dimentions(rank):",  rank2tensor.ndim)
print("shape of the tensor:", rank2tensor.shape)
print("elements along 0 axis:", rank2tensor.shape[0])
print("Elements along the last axis:", rank2tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank2tensor))
print("Total number of elements in our tensor:", tf.size(rank2tensor).numpy()) # simpler version

Datatype of every Element: <dtype: 'float32'>
Number of Dimentions(rank): 4
shape of the tensor: (3, 4, 2, 8)
elements along 0 axis: 3
Elements along the last axis: 8
Total number of elements in our tensor: tf.Tensor(192, shape=(), dtype=int32)
Total number of elements in our tensor: 192


# Indexing Tensors
Tensors can be indexed just like Python Lists

In [20]:
slist=[1,3,4,5,4]
print(slist[:2])

[1, 3]


In [21]:
# get the first 2 values of each dimention 
rank2tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [22]:
# let's change our tensor here and start afresh
rank2tensor=tf.constant([[10,7],[3,7]])

In [23]:
# last item of each of row of our rank 2 tensor
rank2tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 7], dtype=int32)>

In [24]:
# Add in extra dimention to our rank 2 tensor
rank3tensor=rank2tensor[...,tf.newaxis]
print(rank3tensor)

tf.Tensor(
[[[10]
  [ 7]]

 [[ 3]
  [ 7]]], shape=(2, 2, 1), dtype=int32)


`[...,tf.newaxis]` represents `[:,:,tf.newaxis]`

every axis before the new one, include those and add this new one

In [26]:
# Alternative to tf.newaxis
tf.expand_dims(rank2tensor,axis=1) 

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  7]]], dtype=int32)>

In [27]:
tf.expand_dims(rank2tensor,axis=-1) # axis=-1 means expand final axis 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 7]]], dtype=int32)>