# TensorFlow basics for Computer Vision [Deep Learning] Part 1

In [ ]:
import tensorflow as tf

## Types of Tensors

In [ ]:
const=tf.constant(7)
print(const.ndim,const.shape,type(const))

0 () <class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
vec=tf.constant([87,98])
print(vec.ndim,vec.shape,type(vec))

1 (2,) <class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
matrix=tf.constant([[98,87,97,78,9,55,9],[67,76,76,75,9,5,1]])
print(matrix.ndim,matrix.shape,type(matrix))

2 (2, 7) <class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
tensr=tf.constant([[[12,21],[13,43],[12,23]],[[23,24],[23,4],[56,65]]])
print(tensr.ndim,tensr.shape,type(tensr))

3 (2, 3, 2) <class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
# set datatype of tensor by using "dtype" parameter

floatTensr=tf.constant([23,53,0,34,23],dtype=tf.float16)
print(floatTensr)

tf.Tensor([23. 53.  0. 34. 23.], shape=(5,), dtype=float16)


## Tensor casting using `tf.cast()`

In [ ]:
# change the datatype of a tensor using tf.cast() function
intTensr=tf.cast(floatTensr,dtype=tf.int64)
print(intTensr)

tf.Tensor([23 53  0 34 23], shape=(5,), dtype=int64)


In [ ]:
# we can cast to boolean values too, where only zero gives false
boolTensr=tf.cast(floatTensr,dtype=tf.bool)
print(boolTensr)

tf.Tensor([ True  True False  True  True], shape=(5,), dtype=bool)


In [ ]:
# we can turn any tensor object into a vector (1D array) using np.flatten()

import numpy as np
arr=np.array(tensr)
arr=arr.flatten() # only available in numpy library
tensr=tf.constant(arr)
print(tensr)

tf.Tensor([12 21 13 43 12 23 23 24 23  4 56 65], shape=(12,), dtype=int32)


## `tf.eye()`: another way to create diagonal tensors

In [ ]:
eyeTensr=tf.eye(
     num_rows=3,
     num_columns=None,
     # since columns is null, it'll give 3x3 identity matrix
     batch_shape=None,
     dtype=tf.float32,
     name=None
)
print(eyeTensr)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
print(3*eyeTensr) # Scalar Multiplication

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [ ]:
eyeTensr=tf.eye(
     num_rows=3,
     num_columns=5,
     # will give diagonal-matrix wih 1s at leading diagonal
     batch_shape=None,
     dtype=tf.float32,
     name=None
)
print(eyeTensr)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]], shape=(3, 5), dtype=float32)


In [ ]:
eyeTensr=tf.eye(
     num_rows=3,
     num_columns=5,
     batch_shape=(2,3), # 2 tensors with 3 (3,5) matrices each
     dtype=tf.float32,
     name=None
)
print(eyeTensr)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]]], shape=(2, 3, 3, 5), dtype=float32)


## `tf.fill()`: another way to create tensors with a single value

In [ ]:
arr=tf.fill([2,4],9)
print(arr)

tf.Tensor(
[[9 9 9 9]
 [9 9 9 9]], shape=(2, 4), dtype=int32)


In [ ]:
arr2=tf.fill([2,3,4,5],15)
print(arr2)

tf.Tensor(
[[[[15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]]

  [[15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]]

  [[15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]]]


 [[[15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]]

  [[15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]]

  [[15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]
   [15 15 15 15 15]]]], shape=(2, 3, 4, 5), dtype=int32)


## `tf.ones` and `tf.zeros`: only zeros and ones tensors

In [ ]:
ones=tf.ones([3,4])
print(ones)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [ ]:
zeros=tf.zeros([2,3])
print(zeros)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


# `tf.random`: Random Tensors

In [ ]:
normal=tf.random.normal(mean=30,stddev=4,\
                        shape=[4,5],dtype=tf.double,\
                        seed=32,name=None)
# name parameter can be provided to give a name to the operation being performed.
print(normal)

tf.Tensor(
[[27.31506792 31.02382829 28.09655488 28.54825721 32.35985488]
 [27.23645222 25.02776282 29.3740588  30.23386994 27.95143368]
 [34.92283589 32.46990679 30.85703139 32.15418015 34.85951039]
 [34.5457016  29.04404194 37.10091198 34.81103099 32.45139628]], shape=(4, 5), dtype=float64)


In [ ]:
uniform=tf.random.uniform(
    [9,],
    minval=100,
    maxval=1000,
    dtype=tf.int32,
    seed=None,
    name=None
)
print(uniform)

tf.Tensor([631 373 960 228 372 597 855 375 472], shape=(9,), dtype=int32)


`tf.random.uniform`: Generates random values from a uniform distribution.


`tf.random.normal`: Generates random values from a normal (Gaussian) distribution.
tf.random.truncated_normal: Generates random values from a truncated normal distribution.


`tf.random.bernoulli`: Generates random values from a Bernoulli distribution.


`tf.random.categorical`: Generates random values from a categorical distribution.


`tf.random.multinomial`: Generates random values from a multinomial distribution.


`tf.random.gamma`: Generates random values from a gamma distribution.


`tf.random.exponential`: Generates random values from an exponential distribution.


`tf.random.poisson`: Generates random values from a Poisson distribution.


`tf.random.triangular`: Generates random values from a triangular distribution.


`tf.random.uniform_unit_sphere`: Generates random points from a uniform distribution on the unit sphere.

## Indexing in Tensors

In [ ]:
index=tf.constant([3,5,6,7,33,2,4,54])
print(index[0:4])
print(index[1:6])
print(index[6:])

tf.Tensor([3 5 6 7], shape=(4,), dtype=int32)
tf.Tensor([ 5  6  7 33  2], shape=(5,), dtype=int32)
tf.Tensor([ 4 54], shape=(2,), dtype=int32)


In [ ]:
index2=tf.constant([
    [1,2,3],
    [3,34,2],
    [32,34,64],
    [23,34,2]
])
print(index2[0:3,7:3])

tf.Tensor([], shape=(3, 0), dtype=int32)


In [ ]:
a=tf.constant([4,5,4,5,4,5,4,5,4,5,4,5])
print(a[...,1])

tf.Tensor(5, shape=(), dtype=int32)


## Math Operations

#### Max-Min

In [ ]:
x=tf.constant([23,-23,-23,-4,23,-3,-3,-1,-534,23,-23,19])
tf.math.abs(x) # give absolute value

<tf.Tensor: shape=(12,), dtype=int32, numpy=
array([ 23,  23,  23,   4,  23,   3,   3,   1, 534,  23,  23,  19],
      dtype=int32)>

In [ ]:
tf.math.abs(x-a)

<tf.Tensor: shape=(12,), dtype=int32, numpy=
array([ 19,  28,  27,   9,  19,   8,   7,   6, 538,  18,  27,  14],
      dtype=int32)>

In [ ]:
tf.math.minimum(x,a) # compare minimum values at each index b/w 2 same shape tensors

<tf.Tensor: shape=(12,), dtype=int32, numpy=
array([   4,  -23,  -23,   -4,    4,   -3,   -3,   -1, -534,    5,  -23,
          5], dtype=int32)>

In [ ]:
tf.math.maximum(x,a) # same as above but maximum

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([23,  5,  4,  5, 23,  5,  4,  5,  4, 23,  4, 19], dtype=int32)>

argmin and argmax give the indices of minimum and maximum terms

In [ ]:
argmin=tf.math.argmin(x)
print(argmin)

tf.Tensor(8, shape=(), dtype=int64)


In [ ]:
argmax=tf.math.argmax(x)
print(argmax)

tf.Tensor(0, shape=(), dtype=int64)


### `tf.norm`: Calculate Euclidean Norm

In [ ]:
norm=tf.norm(x)
print(norm)

tf.Tensor(537.3322994200144, shape=(), dtype=float64)


#### `tf.math.pow`: element-wise exponentiation of a tensor with a specified exponent

In [ ]:
tf.pow(x,a) # x to the power a

<tf.Tensor: shape=(12,), dtype=int32, numpy=
array([    279841,   -6436343,     279841,      -1024,     279841,
             -243,         81,         -1, -290434288,    6436343,
           279841,    2476099], dtype=int32)>

In [ ]:
tf.pow(x,2)

<tf.Tensor: shape=(12,), dtype=int32, numpy=
array([   529,    529,    529,     16,    529,      9,      9,      1,
       285156,    529,    529,    361], dtype=int32)>

In [ ]:
# above is same as
x**2

<tf.Tensor: shape=(12,), dtype=int32, numpy=
array([   529,    529,    529,     16,    529,      9,      9,      1,
       285156,    529,    529,    361], dtype=int32)>

### `tf.math.exp`: calculate element-wise exponential of a tensor.

In [ ]:
tf.math.exp(x)

<tf.Tensor: shape=(12,), dtype=float64, numpy=
array([9.74480345e+009, 1.02618796e-010, 1.02618796e-010, 1.83156389e-002,
       9.74480345e+009, 4.97870684e-002, 4.97870684e-002, 3.67879441e-001,
       1.22108716e-232, 9.74480345e+009, 1.02618796e-010, 1.78482301e+008])>

### `tf.math.log`: Computes the element-wise natural logarithm of a tensor.

In [ ]:
tf.math.log(x) #log of negative value is Nan
# Logarithms are monotonic functions
# ie they are either ever increasing or ever decreasing
# wrt the independent variable

<tf.Tensor: shape=(12,), dtype=float64, numpy=
array([3.13549422,        nan,        nan,        nan, 3.13549422,
              nan,        nan,        nan,        nan, 3.13549422,
              nan, 2.94443898])>

More Element-wise Operations:

- `tf.math.add`: Performs element-wise addition of tensors.
- `tf.math.subtract`: Performs element-wise subtraction of tensors.
- `tf.math.multiply`: Performs element-wise multiplication of tensors.
- `tf.math.divide`: Performs element-wise division of tensors.

## Reduction Operations

## `tf.reduce_sum`:  sum of elements in a tensor along specified axes.

In [ ]:
rowSum=tf.reduce_sum(matrix,axis=0)
# axis=0 alongside row
print(rowSum)

tf.Tensor([12. 15. 18.], shape=(3,), dtype=float32)


In [ ]:
colSum=tf.reduce_sum(matrix,axis=1)
# axis=1 alongside column
print(colSum)

tf.Tensor([433 309], shape=(2,), dtype=int32)


### `tf.reduce_min()` and `tf.reduce_max` find min and max values along specified axis

In [ ]:
# example
tf.reduce_min(matrix,axis=0)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

### `tf.math.reduce_prod()`: Computes the product of elements along specified axes.

In [ ]:
tf.math.reduce_prod(matrix,axis=1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([  6., 120., 504.], dtype=float32)>

### `tf.math.reduce_mean()`: Computes the mean of elements along specified axes.

In [ ]:
tf.math.reduce_mean(matrix,axis=1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 5., 8.], dtype=float32)>

- `tf.reduce_all`(input_tensor, axis=None, keepdims=False, name=None): Computes the logical AND across dimensions of a boolean tensor.

- `tf.reduce_any`(input_tensor, axis=None, keepdims=False, name=None): Computes the logical OR across dimensions of a boolean tensor.

- `tf.reduce_logsumexp`(input_tensor, axis=None, keepdims=False, name=None): Computes the logarithm of the sum of exponentials of elements across dimensions of a tensor.

- `tf.reduce_variance`(input_tensor, axis=None, keepdims=False, name=None): Computes the variance of elements across dimensions of a tensor.

- `tf.reduce_std`(input_tensor, axis=None, keepdims=False, name=None): Computes the standard deviation of elements across dimensions of a tensor.

## Activation Functions

#### sigmoid

In [ ]:
x=tf.cast(x,dtype=tf.float64)
tf.math.sigmoid(x)
print(np.round(x))

[  23.  -23.  -23.   -4.   23.   -3.   -3.   -1. -534.   23.  -23.   19.]


#### tanh

In [ ]:
z=tf.math.tanh(x)
print(np.round(z,4))

[ 1.     -1.     -1.     -0.9993  1.     -0.9951 -0.9951 -0.7616 -1.
  1.     -1.      1.    ]


### ReLU

In [ ]:
relu=tf.nn.relu(x)
print(relu)

tf.Tensor([23.  0.  0.  0. 23.  0.  0.  0.  0. 23.  0. 19.], shape=(12,), dtype=float64)


### softmax

In [ ]:
soft=tf.nn.softmax(x)
print(soft)

tf.Tensor(
[3.31310611e-001 3.48890528e-021 3.48890528e-021 6.22707842e-013
 3.31310611e-001 1.69269541e-012 1.69269541e-012 1.25074213e-011
 4.15153712e-243 3.31310611e-001 3.48890528e-021 6.06816552e-003], shape=(12,), dtype=float64)


### `tf.math.top_k`:  Top_K values
> find the values and indices of the k largest elements along a specified axis in a tensor. It returns a tuple containing two tensors: the values tensor and the indices tensor.

In [ ]:
values, indices = tf.math.top_k(vec, k=2, sorted=True, name=None)# top 2 values in vec
print(values,indices)

tf.Tensor([98 87], shape=(2,), dtype=int32) tf.Tensor([1 0], shape=(2,), dtype=int32)


## Linear Algebra

## `tf.linalg.matmul`: Matrix Multiplication

- `transpose_a` and `transpose_b`: These are boolean flags that specify whether to transpose the respective input tensors m and n before multiplication. I

    - If set to True, the corresponding tensor will be transposed. In your code, both are set to False, which means no transposition will be performed.

- `adjoint_a` and `adjoint_b`: These are boolean flags similar to transpose_a and transpose_b, but instead of transposing,

    - they indicate whether to take the adjoint (conjugate transpose) of the respective tensors. By default, both are set to False.

- `a_is_sparse` and `b_is_sparse`: These are boolean flags that specify whether the input tensors m and n are sparse tensors.

    - If set to True, the corresponding tensor is considered sparse. In your code, both are set to False, indicating that the tensors are dense.

- `output_type`: This parameter specifies the data type of the resulting tensor.

    - If not specified (set to None), the data type is inferred based on the input tensors.

- `name`: An optional name for the operation.

In [ ]:
m=tf.reshape(x,(3,4))
n=tf.reshape(a,(4,3))
m=tf.cast(m,dtype=tf.int32)

In [ ]:
matmul=tf.linalg.matmul(m,n,transpose_a=False,transpose_b=False,adjoint_a=False,adjoint_b=False,a_is_sparse=False,b_is_sparse=False,output_type=None,name=None)
print(matmul)

tf.Tensor(
[[ -135  -108  -135]
 [   60    84    60]
 [-2018 -2617 -2018]], shape=(3, 3), dtype=int32)


In [ ]:
# method 2 of matmul
matmul=m@n
print(matmul)

tf.Tensor(
[[ -135  -108  -135]
 [   60    84    60]
 [-2018 -2617 -2018]], shape=(3, 3), dtype=int32)


### `tf.linalg.matrix_transpose` or `tf.transpose`: find transpose of tensor

In [ ]:
# transpose
print(tf.transpose(m)) # lowercase t in transpose
print(m@tf.transpose(m))

tf.Tensor(
[[  23   23 -534]
 [ -23   -3   23]
 [ -23   -3  -23]
 [  -4   -1   19]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[  1603    671 -12358]
 [   671    548 -12301]
 [-12358 -12301 286575]], shape=(3, 3), dtype=int32)


### `tf.lingalg.band_part`: used to extract a specific band or diagonal from a matrix. It allows you to set all elements outside the desired band or diagonal to zero.

- *input*: The input tensor from which the band or diagonal is extracted.

- *num_lower*: An integer representing the number of lower diagonals to keep. Diagonals below this value will be set to zero.

- *num_upper*: An integer representing the number of upper diagonals to keep. Diagonals above this value will be set to zero.

- *name* (optional): A name for the operation.




In [ ]:
import tensorflow as tf

# Create a matrix
matrix=tf.constant([[1,2,3],[4,5,6],[7,8,9]])

# Extract the main diagonal
diagonal=tf.linalg.band_part(matrix,0,0)

# Extract the upper triangle
upper_triangle=tf.linalg.band_part(matrix,0,-1)

# Extract the lower triangle
lower_triangle=tf.linalg.band_part(matrix,-1,0)

# Extract a band around the main diagonal
band=tf.linalg.band_part(matrix,1,1)

print("Diagonal:")
print(diagonal)

print("Upper Triangle:")
print(upper_triangle)

print("Lower Triangle:")
print(lower_triangle)

print("Band:")
print(band)


Diagonal:
tf.Tensor(
[[1 0 0]
 [0 5 0]
 [0 0 9]], shape=(3, 3), dtype=int32)
Upper Triangle:
tf.Tensor(
[[1 2 3]
 [0 5 6]
 [0 0 9]], shape=(3, 3), dtype=int32)
Lower Triangle:
tf.Tensor(
[[1 0 0]
 [4 5 0]
 [7 8 9]], shape=(3, 3), dtype=int32)
Band:
tf.Tensor(
[[1 2 0]
 [4 5 6]
 [0 8 9]], shape=(3, 3), dtype=int32)


In [ ]:
# another way to do this

# Create a matrix
matrix=tf.constant([[1,2,3],[4,5,6],[7,8,9]])

# Extract the main diagonal
diagonal=tf.linalg.diag_part(matrix)
print(diagonal)

tf.Tensor([1 5 9], shape=(3,), dtype=int32)


In [ ]:
tf.linalg.band_part(matrix,0,0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]], dtype=int32)>

### `tf.linalg.svd`: Singular Value Decomposition

 > matrix factorization technique used in linear algebra. It decomposes a matrix into three constituent matrices, providing useful insights into the properties and structure of the original matrix.

Given a matrix A, the SVD factorizes it as follows:

**`A = U * S * V^T`** where:

- U is an orthogonal matrix (U^T * U = U * U^T = I), representing the left singular vectors of A.
- S is a diagonal matrix containing the singular values of A.
- V^T is the transpose of an orthogonal matrix V, representing the right singular vectors of A.


The singular values in S are non-negative and arranged in descending order along the diagonal.
The singular vectors in U and V are unit vectors that form an orthonormal basis for the column and row spaces of A, respectively.
<br>
<hr>
<br>
In tensorflow, it's like following

In [ ]:
matrix=tf.cast(matrix,dtype=tf.float32)
s,u,v=tf.linalg.svd(matrix)
print(s,u,v)

tf.Tensor([1.6848103e+01 1.0683696e+00 2.8763120e-07], shape=(3,), dtype=float32) tf.Tensor(
[[ 0.21483716  0.8872305  -0.40824857]
 [ 0.5205872   0.24964423  0.8164965 ]
 [ 0.8263376  -0.3879429  -0.4082481 ]], shape=(3, 3), dtype=float32) tf.Tensor(
[[ 0.47967106 -0.77669096  0.40824836]
 [ 0.5723676  -0.07568647 -0.81649655]
 [ 0.6650643   0.62531805  0.40824822]], shape=(3, 3), dtype=float32)


- matrix is a rank 2 tensor
- s is a tensor of singular values
- u is a tensor of left singular values
- v is a tensor of right singular values

### `tf.linalg.trance`: Compute the trance of a tensor
> The trace of a tensor is a scalar value that represents the sum of the elements along the leading diagonal of the tensor

In [ ]:
tf.linalg.trace(matrix, name=None)

<tf.Tensor: shape=(), dtype=float32, numpy=15.0>

### `tf.linalg.det()`: Compute the determinant of Tensor
> The determinant represents a scalar value that characterizes certain properties of the matrix.

In [ ]:
tf.linalg.det(matrix) # only works with sq matrices

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

## `tf.linalg.inv()`: Inverse of a matrix
only works if the vector is non-singular, ie it's determinant is non-zero scalar value.

In [ ]:
newarr=tf.random.uniform([3,3,4,4],dtype=tf.float32)
tf.linalg.inv(newarr) # only works with sq matrices
# that are non-singular

<tf.Tensor: shape=(3, 3, 4, 4), dtype=float32, numpy=
array([[[[-2.05815569e-01, -1.29703033e+00, -1.11068416e+00,
           1.78049469e+00],
         [ 2.15837717e+00, -3.34651923e+00,  1.34968305e+00,
          -5.27091086e-01],
         [ 4.27619457e-01,  2.09197998e+00,  2.81985492e-01,
          -1.03872073e+00],
         [-2.52408981e+00,  2.21167827e+00, -4.18799311e-01,
           1.18505669e+00]],

        [[-7.97803044e-01,  4.27582145e-01,  3.50974530e-01,
           6.86855137e-01],
         [ 9.01733100e-01,  2.45475078e+00, -5.16888237e+00,
           2.85957766e+00],
         [ 1.82960719e-01, -1.54897118e+00,  1.89441836e+00,
          -2.15974644e-01],
         [ 2.99410671e-01, -2.91068345e-01,  1.79613078e+00,
          -1.94421065e+00]],

        [[-2.28429294e+00,  1.45817912e+00, -1.34051764e+00,
           2.33748531e+00],
         [ 1.14468895e-01, -4.44002360e-01,  1.51055419e+00,
           9.43744257e-02],
         [ 4.77475929e+00, -5.60140753e+00,  2.03320

### `tf.linalg.ein()`: EigenVectors and EigenValues


In [ ]:
matrix=tf.constant([[1.0,2.0],[3.0,4.0]],dtype=tf.float32)

# Compute eigenvalues and eigenvectors
eigenvalues,eigenvectors=tf.linalg.eig(matrix)
print(eigenvalues,eigenvectors)

tf.Tensor([-0.37228122+0.j  5.372281  +0.j], shape=(2,), dtype=complex64) tf.Tensor(
[[-0.8245648 +0.j -0.4159736 +0.j]
 [ 0.56576747+0.j -0.9093768 +0.j]], shape=(2, 2), dtype=complex64)


###  `tf.linalg.cross`: Compute the pairwise cross product

In [ ]:
e=tf.constant([123,3,34])
r=tf.constant([23,34,23])

tf.linalg.cross(r,r)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0], dtype=int32)>