# Min/Max Functions

- Used in artificial neural networks (ANNs) to normalize the inputs or outputs of the network.
- Normalization is an important step in the preprocessing of data in ANNs as it helps to ensure that the inputs are within a similar range of values, which can make the training process faster and more effective.

- These functions can be used to calculate the range of values in a dataset and then normalize the data by subtracting the minimum value and dividing by the range.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
numbers = [1, 2, 3, 4, 5]

# Find the minimum and maximum values in the list
min_value = np.min(numbers)
max_value = np.max(numbers)

# Calculate the range of values
range_value = max_value - min_value

# Normalize the data
normalized_numbers = [(x - min_value) / range_value for x in numbers]

print(normalized_numbers)


[0.0, 0.25, 0.5, 0.75, 1.0]


## Argmax/Argmin Functions

- `argmax` and `argmin` are functions in Python that are used to find the indices of the maximum and minimum values in a list, respectively.
- In the context of artificial neural networks (ANNs), these functions can be used to determine the class label of a sample based on the output of the neural network.

<br />

- For example, in a multi-class classification problem, the output of the neural network is a vector of probabilities, where each element represents the probability of the sample belonging to a particular class.
- The class label can be determined by finding the index of the maximum probability in the output vector, which can be done using the `argmax` function.

In [ ]:
output = [0.1, 0.2, 0.3, 0.4]

# Find the index of the maximum value in the list
class_label1 = np.argmax(output)
class_label2 = np.argmin(output)

# another way of doing this
class_label_X = output.index(max(output))
class_label_Y = output.index(min(output))

print('Min, Max indices: %g,%g' %(class_label1,class_label2))
print(class_label_X)
print(class_label_Y)
# Output: 3

Min, Max indices: 3,0
3
0


In [ ]:
# repating this with a matrix
M=np.array([[0,1,10],
            [20,8,5]])
print(M), print(' ')

#various minima in this matrix
minvals1=np.min(M) # minimum element of entire matrix
minvals2=np.min(M, axis=0) #minimum element of each column (across rows)
minvals3=np.min(M, axis=1) # minimum element of each row (across columns)
print(minvals1)
print(minvals2)
print(minvals3)

[[ 0  1 10]
 [20  8  5]]
 
0
[0 1 5]
[0 5]


### Using Pytorch

In [ ]:
import torch
import torch.nn.functional as func

In [ ]:
v=torch.Tensor([1,40,2,-3])

# find and report min and max values
maxval=torch.min(v)
minval=torch.max(v)

print('Min, Max indices: %g,%g' %(minval,maxval))

minidx=torch.argmin(v)
maxidx=torch.argmax(v)

print('Min, Max indices: %g, %g' %(minidx, maxidx))


Min, Max indices: 40,-3
Min, Max indices: 3, 1


In [ ]:
M=torch.tensor([[0,1,10],
            [20,8,5]])
print(M), print(' ')

#various minima in this matrix
min1=torch.min(M) # minimum element of entire matrix
min2=torch.min(M, axis=0) #minimum element of each column (across rows)
min3=torch.min(M, axis=1) # minimum element of each row (across columns)

print(min2), print(' ')
print(min2.values), print(' ')
print(min3.indices), print(' ')

tensor([[ 0,  1, 10],
        [20,  8,  5]])
 
torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1]))
 
tensor([0, 1, 5])
 
tensor([0, 2])
 


(None, None)

In [ ]:
type(min2)

torch.return_types.min