# Numpy Primer pt3 

In [1]:
import numpy as np

###  Other Useful numpy Operations 

In [42]:
a=np.array([22,3,56,34,2,45,6,74]) # New Vector

expn=np.exp(a) # gives e^x value

natlog=np.log(a) # gives natural log value

clipped=np.clip(a,None,20) # only includes values below threshold

print(expn,'\n\n',natlog,'\n\n',clipped)

[3.58491285e+09 2.00855369e+01 2.09165950e+24 5.83461743e+14
 7.38905610e+00 3.49342711e+19 4.03428793e+02 1.37338298e+32] 

 [3.09104245 1.09861229 4.02535169 3.52636052 0.69314718 3.80666249
 1.79175947 4.30406509] 

 [20  3 20 20  2 20  6 20]


In [45]:
# Min-Max values

max=np.max(a)
min=np.min(a)


# Find the indices of the maximum or minimum values in an array.
position_of_max_element=np.argmax(a) 
position_of_min_element=np.argmin(a)

sortindices=np.argsort(a) #Return the indices that would sort an array.

sorted_a=np.sort(a) # Sort the array

print(max,min,position_of_min_element,position_of_max_element,'\n\n',sortindices,'\n\n',sorted_a)

74 2 4 7 

 [4 1 6 0 3 5 2 7] 

 [ 2  3  6 22 34 45 56 74]


In [3]:
# let's create an array again

arr=np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
# Reshape the array

reshaped=np.reshape(arr,(2,5))
print(reshaped,'\n','\n',reshaped.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 
 
 (2, 5)


###  numpy **Concatenate**
join 2 arrays either row-wise or column-wise

> Useful in One Hot Encoding with multiple categorical variables

In [33]:
# Concatenate arrays

binarr1=[1 if a>0.5 else 0 for a in np.random.random(size=4)]
binarr2=[1 if a>0.7 else 0 for a in np.random.random(size=4)]
print(binarr1,'\n',binarr2)

[1, 1, 1, 0] 
 [0, 1, 1, 0]


In [25]:
# works only on numpy arrays
b1=np.array(binarr1)
b2=np.array(binarr2)

res=np.concatenate((b1,b2),axis=0) # concatenate a1 and a1 row-wise
print(res)

[1 0 0 1 0 0 0 0]


In [32]:
# For column-wise concatenation we need 2D arrays
b1=np.reshape(b1,(2,2))
b2=np.reshape(b2,(2,2))
print(b1,'\n','\n',b2,'\n')

res=np.concatenate((b1,b2),axis=1)
print(res)

[[1 0]
 [0 1]] 
 
 [[0 0]
 [0 0]] 

[[1 0 0 0]
 [0 1 0 0]]


# **Linear Algebra Calculations** in `numpy`

In [69]:
# Let's make a square matrix for this
sq=np.random.randint(5,20,(3,3))


inverse=np.linalg.inv(sq) # Compute the inverse of a square matrix.

determinant=np.linalg.det(sq) #  Compute the determinant of a square matrix.

eigenvectors=np.linalg.eig(sq) #  Compute the eigenvalues and eigenvectors of a square matrix.

print(inverse,'\n\n',determinant,'\n\n', eigenvectors)

[[ 0.02083333  0.09375    -0.05208333]
 [ 0.625      -0.6875     -0.0625    ]
 [-0.77083333  0.78125     0.17708333]] 

 -192.0 

 (array([31.8604919 ,  4.48358316, -1.34407506]), array([[-0.57968892, -0.37091524,  0.13346188],
       [-0.44461478, -0.31457551, -0.69790793],
       [-0.68284584,  0.87376434,  0.70364227]]))


### numpy **split**

In [57]:
arr=np.array([1,2,3,4,5,6,7,8])

subarrays=np.split(arr,4) # split array into 4 subarrays
print(subarrays)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [59]:
# splitting at specific indices

subarrays=np.split(arr,[2,5])
print(subarrays)

[array([1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [61]:
# splitting 2D array along second axis

arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
subarrays=np.split(arr,3,axis=1)
print(subarrays)

[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


In [66]:
# Matrix Multiplication method 2

a1=np.random.randint(0,100,(2,3))
print(a1,"\n\n")

a2=np.random.randint(0,100,(3,5))
print(a2,"\n\n")

res=np.matmul(a1,a2)
print(res)

[[86 97 81]
 [11 73 54]] 


[[77 90 73 91 67]
 [40 16 89 81 77]
 [17 18 60 53 77]] 


[[11879 10750 19771 19976 19468]
 [ 4685  3130 10540  9776 10516]]


## numpy  `expand_dims()`

In [70]:
# Expand dimensions at the beginning (axis 0)

arr=np.array([1,2,3])
expanded_arr=np.expand_dims(arr,axis=0)
print(expanded_arr.shape)  # Output: (1, 3)

(1, 3)


In [72]:
# Expand dimensions at the end (default behavior, axis -1):

expanded_arr = np.expand_dims(arr,axis=-1)
print(expanded_arr.shape)  # Output: (3, 1)

(3, 1)


In [73]:
# Expand dimensions of a 2D array:

arr=np.array([[1,2],[3,4]])
expanded_arr=np.expand_dims(arr,axis=0)
print(expanded_arr.shape)  # Output: (1, 2, 2)

(1, 2, 2)


In [74]:
# Expand dimensions of a higher-dimensional array:

arr=np.ones((2,3,4))
expanded_arr = np.expand_dims(arr,axis=1)
print(expanded_arr.shape)  # Output: (2, 1, 3, 4)


(2, 1, 3, 4)
