# Numpy Primer pt2

In [114]:
# import dependencies
import numpy as np

In [115]:
# Make vectors ie 1D arrays in numpy

a1=np.array([1,3,5,5,7,2,1],dtype='int64')
a2=np.array([4,6,7,4,2,4,3],dtype='int64')

TypeError: ignored

In [100]:
# Make a matrix ie 2D arrays in numpy
mat=np.matrix('1 3 5 6; 3 5 7 8')
print(mat,np.shape(mat))

# a better way to make a numpy matrix
np.array=([[3,4,5,6,7,2],[9,7,6,0,7,8],[5,0,8,6,4,3]])
print(np.shape(array), "\n", array) # np.shape gives as you can guess, shape of array

[[1 3 5 6]
 [3 5 7 8]] (2, 4)
(3, 6) 
 [[3, 4, 5, 6, 7, 2], [9, 7, 6, 0, 7, 8], [5, 0, 8, 6, 4, 3]]


## Shuffle
Shuffles the rows randomly in a numpy array object
> Extremely important for Stochastic Gradient Descent

In [56]:
# now shuffle the rows
np.random.seed(42)
np.random.shuffle(array)
print(array)

[[3, 4, 5, 6, 7, 2], [9, 7, 6, 0, 7, 8], [5, 0, 8, 6, 4, 3]]


## Basic Operations 

In [61]:
# you can perform basic arithmetic operations on numpy arrays
# in all these, corresponding elements are affected by each other only
# hence dimention of each vector ie shape needs to be same for them to work

print(a1+a2,"\n")
print(a1-a2,"\n")
print(a1/a2,"\n")
print(a1*a2,"\n")
print(a1**a2,"\n") # a1 to the power of a2

[ 5  9 12  9  9  6  4] 

[-3 -3 -2  1  5 -2 -2] 

[0.25       0.5        0.71428571 1.25       3.5        0.5
 0.33333333] 

[ 4 18 35 20 14  8  3] 

[    1   729 78125   625    49    16     1] 



In [96]:
# another way to do this
add=np.add(a1,a2) # Add two arrays element-wise.
subs=np.subtract(a1,a2) # Subtract two arrays element-wise.
mult=np.multiply(a1,a2) # Multiply two arrays element-wise.
divd=np.divide(a1,a2) # Divide two arrays element-wise.
divd=[np.round(x,2) for x in divd] 
print(add,"\n",subs,"\n",mult,"\n",divd)

[ 5  9 12  9  9  6  4] 
 [-3 -3 -2  1  5 -2 -2] 
 [ 4 18 35 20 14  8  3] 
 [0.25, 0.5, 0.71, 1.25, 3.5, 0.5, 0.33]


In [76]:
sum=np.sum([a1,a2]) #add arrays
print(sum,"\n")

dot=np.dot(a1,a2) # dot product of vectors (matrix multiplication)
print(dot,"\n")

res=np.transpose(array) # Transpose the matrix/vector
print(res,"\n")

mean=np.mean(a1) # mean of an array
std_dev=np.std(a1) # standard deviation of the array
print(mean, std_dev,"\n")

# Other basic operations
sqrt=np.sqrt(25)
ceil=np.ceil(34.533)
floor=np.floor(67.4545)
print(sqrt,ceil,floor,"\n")

# Trignometric Functions

sin=np.sin(4/5)
cos=np.cos(3/5)
tan=np.tan(23)

# Inverse Trignometric Functions

arcsin=np.arcsin(0.4)
arccos=np.arccos(0.5)
arctan=np.arctan(0.01)

# Hyperbolic Trignometric Functions (angle = length of arc/radius but the arc is of hyperbola instead of a circle)

hypersin=np.sinh(434)
hypercos=np.cosh(34)
hypertan=np.tanh(4334) #### VERY IMPORTANT FUNCTION (ACTIVATION FUNCTION)

print(sin,cos,tan,arcsin,arccos,arctan,hypersin,hypercos,hypertan)

54 

102 

[[3 9 5]
 [4 7 0]
 [5 6 8]
 [6 0 6]
 [7 7 4]
 [2 8 3]] 

3.4285714285714284 2.1285234893930483 

5.0 35.0 67.0 

0.7173560908995228 0.8253356149096783 1.5881530833912738 0.41151684606748806 1.0471975511965979 0.009999666686665238 1.5232639018720384e+188 291730871263727.44 1.0


In [63]:
# Round-off and Truncation 

a=np.trunc(5.34343) # removes decimal values ie truncates
b=np.round(5.34343,2) # rounds the vaulue till 2nd decimal value
print(a,b)

5.0 5.34


In [84]:
# Euclidian Distance between 2 Vectors

# euclidean distances are helful in algorithms like KNN
# they also help in finding cosine_similarity

d=((a1-a2)**2).sum()
euc_dist=np.sqrt(d)
print(euc_dist)

7.483314773547883


In [82]:
# Standard Deviation and Variance (manually using numpy)

x=a1 # copy the array here

x_bar=np.mean(a1)
#OR
x_bar=a1.mean()

# x.shape[0] gives the no of elements in a row of the array
var=np.sum((x-x_bar)**2)/(x.shape[0]-1) # Variance
std_dev=np.sqrt(var)
print(var, std_dev)

5.285714285714286 2.29906813420444
