# numpy **PRIMER** pt1


In [3]:
import numpy as np

In [ ]:
# array of zeroes

a=np.zeros(10,dtype=int)
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
# matrix of value 'x'

a=np.full((2,4),5,dtype=float) # new array of shape 2x4 and value 5p
print(a)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [ ]:
a=np.arange(10) # new array from zero->n
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a=np.arange(2,20,2) # (start_val,end_val,distance)
print(a)

[ 2  4  6  8 10 12 14 16 18]


we can do all this using loops too, but this is more optimized method since compilation happens in c language

## numpy **linspace**

generates equidistant values randomly between a given range

In [ ]:
b=np.linspace(2,10,dtype=float) # give random values b/w (a,b)
print(b)

[ 2.          2.16326531  2.32653061  2.48979592  2.65306122  2.81632653
  2.97959184  3.14285714  3.30612245  3.46938776  3.63265306  3.79591837
  3.95918367  4.12244898  4.28571429  4.44897959  4.6122449   4.7755102
  4.93877551  5.10204082  5.26530612  5.42857143  5.59183673  5.75510204
  5.91836735  6.08163265  6.24489796  6.40816327  6.57142857  6.73469388
  6.89795918  7.06122449  7.2244898   7.3877551   7.55102041  7.71428571
  7.87755102  8.04081633  8.20408163  8.36734694  8.53061224  8.69387755
  8.85714286  9.02040816  9.18367347  9.34693878  9.51020408  9.67346939
  9.83673469 10.        ]


What's special about linspace is every instance is equi-distant from other



In [ ]:
print(b[1]-b[0], b[2]-b[1], b[3]-b[2]) # same distances

0.16326530612244916 0.16326530612244872 0.16326530612244916


In [ ]:
b=np.linspace(2,10,5) # (a,b,c) gives c equidistant values b/w a & b

In [ ]:
# identity matrix of order (x)
b=np.identity(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 2-D array with ones on the leading diagonal and zeros elsewhere.
b=np.eye(3,4)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


## numpy **random**
generates random values

In [12]:
# generate a single random value between 0 and 1

r=np.random.random()
print(r,"\n")

# generate (x) uniformy distributed random values b/w 0 and 1 (of any specified shape)

c=np.random.rand(10)
print(c)



0.007022578218907172 

[0.07440057 0.1398569  0.33304048 0.9817316  0.50516944 0.8750213
 0.15418858 0.34318107 0.51347159 0.38349431]


In [ ]:
# Hence, to get any uniform random values that're between say 0 and 1000

c=np.random.rand(5)*1000
print(c)

[ 20.5844943  969.90985216 832.4426408  212.33911068 181.82496721]


In [9]:
# but what if I want (x) uniform values between a specified range (a and b) instead of 0 and some number 

# generates (x) random numbers from a uniform distribution within a specified range.

c=np.random.uniform(-10,10,size=10) # (start_val,end_val,x)
print(c)

[-1.53836882 -6.22312555  6.46234572  9.9108253  -8.19232333 -5.39626615
  3.1094453   0.49534914 -6.89294506  2.6531438 ]


In [ ]:
# generates (x) random integers within a specified range

c=np.random.randint(0,100,size=10) # (start_val,end_val,x)
print(c)

[87 79 55 15  1 19 42 66 63 66]


In [ ]:
# generate (x) random values with gaussian/normal distribution 

c=np.random.normal(10,5,size=10) # (mean,std_dev,x)
print(c)

[ 4.49183882  0.56932892  7.92399349  6.31996339  8.06539907  6.56094539
  2.26507988  5.84199326 15.55554497 15.33563993]


In [6]:
# generate (x) random values with exponential distribution

c=np.random.exponential(3,size=10) # (e^3, x)
print(c)

[6.62427312 5.44542532 0.14857105 7.98525887 1.03576085 1.56284614
 3.0726149  0.79448925 0.96731838 8.08910001]


In [8]:
# More random number distbutions

# generates random numbers from a Binomial distribution with specified number of trials and success probability.
b=np.random.binomial(10,0.5,size=10) # (trials, success_probability, x)
print(b,"\n")

# generates random numbers from a Gamma distribution with specified shape and scale parameters.
g=np.random.gamma(2,1,size=10) # (shape, scale, x)
print(g,"\n")

# generates random numbers from a Poisson distribution with specified lambda (mean) parameter
p=np.random.poisson(2,size=10) # (lambda[mean], x)
print(p,"\n")

# generates random numbers from a log-normal distribution with specified mean and standard deviation of the underlying normal distribution.
l=np.random.lognormal(0,1,size=10) # (mean, std_dev, x)
print(l,"\n")

[6 5 3 4 3 6 4 3 5 3] 

[2.71611436 0.4915566  5.35499207 4.46007826 0.52005089 3.68278198
 1.34353327 4.79705627 2.41125905 1.34416364] 

[0 3 1 3 4 2 5 3 0 5] 

[0.62964591 3.0375497  0.89894953 0.25205888 2.44039324 0.60275936
 0.4904356  5.14197103 3.54322547 0.86070007] 



In [ ]:
# another way for logarithmic distribution

c=np.random.rand(10)
# Apply logarithmic transformation to approximate a logarithmic distribution
c=np.exp(c)-1 
print(c)

[0.00808241 0.85300572 0.49919238 0.85480072 1.35220208 1.33661306
 1.09010404 1.39265245 1.1035297  0.02827208]


problem is, these values change everytime we execute these commands

### So we'll introduce ***Random Seed*** to ensure reproducibility of these values

In [ ]:
np.random.seed(42) # this ensures values remain consistent and reproducible
c=np.random.randint(0,100,size=10)
print(c)

# Here, any x=non zero value in random.seed(x) ensure that our c generates reproducible values 

[51 92 14 71 60 20 82 86 74 74]


### Instead of size, we can put `(row,column)` input to have a matrix of random inputs instead of just simple arrays




In [21]:
# Examples

# generate uniform random values between 0 and 1 for a matrix of size (1,3)
c=np.random.rand(1,3)
print(c,"\n","\n")

# generate normal random values for a matrix of size (3,5)
c=np.random.normal(10,2,(3,5))
print(c,"\n","\n")

# generate uniform random values between (-5 and 5) for a matrix of size (3,3)
c=np.random.uniform(-5,5,size=(3,3))
print(c,"\n,'\n")

[[0.01227376 0.96006941 0.21925673]] 
 

[[12.3625081   8.11418005 10.05892033  9.96746241 10.38645417]
 [ 9.26418949 11.60223038 10.55423885 14.25887078  9.63343448]
 [11.50561299 11.09017517 11.01131771 10.02939554  8.20206146]] 
 

[[ 4.44992567  0.6934493  -3.04654434]
 [-1.20652454  4.85618089 -3.14001521]
 [-0.7596492  -0.46165341 -3.74840092]] 
,'



### other distributions for random values


`np.random.pareto()`: Generates random numbers from a Pareto distribution with specified shape parameter.

`np.random.geometric()`: Generates random numbers from a geometric distribution with specified success probability.

`np.random.hypergeometric()`: Generates random numbers from a hypergeometric distribution with specified population sizes and sample size.

`np.random.multinomial()`: Generates random numbers from a multinomial distribution with specified number of trials and probabilities for each category.

`np.random.triangular()`: Generates random numbers from a triangular distribution within a specified range.

`np.random.vonmises()`: Generates random numbers from a von Mises distribution (circular distribution) with specified mean and concentration parameter.

`np.random.wald()`: Generates random numbers from a Wald (inverse Gaussian) distribution with specified mean and scale parameters.

`np.random.weibull()`: Generates random numbers from a Weibull distribution with specified shape parameter.

## numpy **indexing**

In [ ]:
li=[3,5,6,77,65,4,3,2,2,2,4,7,64,3,2,3,4,5,6,6,5,3,13]

arr=np.array(li)
print(li, arr) # same

[3, 5, 6, 77, 65, 4, 3, 2, 2, 2, 4, 7, 64, 3, 2, 3, 4, 5, 6, 6, 5, 3, 13] [ 3  5  6 77 65  4  3  2  2  2  4  7 64  3  2  3  4  5  6  6  5  3 13]


In [ ]:
print(arr.data)
print(arr.shape)
print(arr.size)
print(arr.dtype) 
print(arr.strides) #  to move to the next element along the rows (axis 0), you need to skip 8 bytes in memory,

(23,)
23
int64
(8,)


In [ ]:
li_2d=[[32,4,5,34],[23,52,3,5],[23,64,234,5],[5,3,6,8]]
arr_2d=np.array(li_2d)
print(arr_2d)

[[ 32   4   5  34]
 [ 23  52   3   5]
 [ 23  64 234   5]
 [  5   3   6   8]]


In [ ]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.size)
print(arr_2d.dtype) 
print(arr_2d.strides)

(4, 4)
16
int64
(32, 8)


## numpy **Slicing**

In [ ]:
# in 1D array
print(arr)

print(arr[3]) # single value at index 3

print(arr[0:3]) # from 0 to 2
print(arr[:5]) # all row values till columnidx=5 (0 to 4)
print(arr[2:5]) # from 2 to 4

[ 3  5  6 77 65  4  3  2  2  2  4  7 64  3  2  3  4  5  6  6  5  3 13]
77
[3 5 6]
[ 3  5  6 77 65]
[ 6 77 65]


In [ ]:
# in 2D array
print(arr_2d,"\n")

print(arr_2d[1,2],"\n") # single value at rowidx=1 and columnidx=2

print(arr_2d[2:],"\n") # exclude first 2 arrays only and print rest
print(arr_2d[:3],"\n") # exclude first 3 columns each array and print

# Slice the second row, but only the first three elements
print(arr_2d[1, :3],"\n") 

# Slice the first three rows, but only the third column
print(arr_2d[:3, 2],"\n")

# Slice the third row, but only the first three elements
print(arr_2d[2, :3],"\n") 

# Slice the fourth row, starting from index 1 until the end of the row
print(arr_2d[3, 1:],"\n")

# Slice the first 3 rows, but only the first column
print(arr_2d[0:3, 0],"\n")  

# Slice the third row, but only the first 2 columns
print(arr_2d[2, 0:2],"\n")  

# Slice rows 2 to 4-1=3 (inclusive), and columns 1 to 3-1=2 (inclusive)
print(arr_2d[2:4,1:3],"\n")

[[ 32   4   5  34]
 [ 23  52   3   5]
 [ 23  64 234   5]
 [  5   3   6   8]] 

3 

[[ 23  64 234   5]
 [  5   3   6   8]] 

[[ 32   4   5  34]
 [ 23  52   3   5]
 [ 23  64 234   5]] 

[23 52  3] 

[  5   3 234] 

[ 23  64 234] 

[3 6 8] 

[32 23 23] 

[23 64] 

[[ 64 234]
 [  3   6]] 

